name: Build test

on:
  create:
    branches:
  push:
    branches: [ main, dev, vanilla, release/*, release-vanilla/* ]
  pull_request:
    branches: [ main, dev, vanilla, release/*, release-vanilla/* ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build test
      run: |
        sudo apt install -y jq
        bash utils/build.sh
